{
    "jquery": true,
    "node": true,
    "browser": true,
    "globals": {
        "App": true,
        "Backbone": true,
        "_": true
    },
    "curly": true,
    "camelcase": false,
    "evil": false,
    "trailing": true,
    "sub": true,
    "eqeqeq": true,
    "eqnull": false,
    "devel": true,
    "smarttabs": false,
    "laxbreak": false,
    "laxcomma": true,
    "loopfunc": true,
    "indent": 2,
    "bitwise": true,
    "noarg": true,
    "noempty": true,
    "nonew": true,
    "undef": true,
    "boss": true,
    "newcap": true,
    "quotmark": "single",
    "unused": true,
    "strict": true,
    "maxparams": 5,
    "maxdepth": 5,
    "maxstatements": 20,
    "maxcomplexity": 10
}
